package GUI.dialogs;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Collection;
import java.util.Vector;
import model.*;

public class CreatedWarningsDialog extends javax.swing.JDialog
{
	private static final long serialVersionUID = -1444014212561992995L;
	
	private Collection<Warning> warnings;
  /** Creates new form CreatedWarningsDialog */
  public CreatedWarningsDialog(java.awt.Frame parent, Collection<Warning> createdWarnings)
  {
    super(parent, true);
    this.warnings = createdWarnings;
    initComponents();
    fillTable();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents()
  {

    titleLabel = new javax.swing.JLabel();
    okButton = new javax.swing.JButton();
    contentPanel = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    warningTable = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
    titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleLabel.setText("Erstellte Warnungen:");

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });

    jScrollPane1.setViewportView(warningTable);

    javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
    contentPanel.setLayout(contentPanelLayout);
    contentPanelLayout.setHorizontalGroup(
      contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(contentPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        .addContainerGap())
    );
    contentPanelLayout.setVerticalGroup(
      contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(contentPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(533, Short.MAX_VALUE)
        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(okButton)
        .addContainerGap())
    );
    
    // dialog mittig auf dem bildschirm setzen
    DialogHelper.setToCenterScreen(this);
    
    pack();
  }// </editor-fold>

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)
  {
    this.dispose();
  }
  
  private void fillTable()
  {
    Vector columnNames = new Vector();
    columnNames.add("MahnungsNr.");
    columnNames.add("KundenNr.");
    columnNames.add("Anzahl Filme");
    columnNames.add("Rückgabefrist");
    
     warningTable.setModel(new javax.swing.table.DefaultTableModel(
				createWarningEntries(), columnNames));
  }
  
  private Vector createWarningEntries()
  {
    Vector dataRows = new Vector();
    for(Warning w : this.warnings)
    {
      Vector row = new Vector();
      row.add(w.getID());
      row.add(w.getInRent().getCustomer().getID());
      row.add(w.getInRent().getVideoUnits().size());
      row.add(w.getInRent().getReturnDate());
      
      dataRows.add(row);
    }
    
    return dataRows;
  }
  
  
  // Variables declaration - do not modify
  private javax.swing.JPanel contentPanel;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton okButton;
  private javax.swing.JLabel titleLabel;
  private javax.swing.JTable warningTable;
  // End of variables declaration
  
}