package GUI.dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * InfoDialog.java
 * @author Christopher Bertels (chbertel@uos.de)
 * 25.09.2008
 *
 * InfoDialog mit Informationen zum Projekt.
 */
public class InfoDialog extends javax.swing.JDialog
{
	private static final long serialVersionUID = -3198329999601151234L;

	  /** Creates new form InfoDialog */
	  public InfoDialog(java.awt.Frame parent, boolean modal)
	  {
	    super(parent, modal);
	    initComponents();
	  }
	  
	  /** This method is called from within the constructor to
	   * initialize the form.
	   * WARNING: Do NOT modify this code. The content of this method is
	   * always regenerated by the Form Editor.
	   */
	  // <editor-fold defaultstate="collapsed" desc="Generated Code">
	  private void initComponents()
	  {
	
	    okButton = new javax.swing.JButton();
	    jScrollPane1 = new javax.swing.JScrollPane();
	    textPane = new javax.swing.JTextPane();
	    textPane.setEditable(false);
	
	    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	    setTitle("V-Unit: Informationen");
	
	    okButton.setText("OK");
	    okButton.addActionListener(new ActionListener(){
			
			public void actionPerformed(ActionEvent e)
			{
				okButtonActionPerformed(e);
			}
	    });
	
	    textPane.setText("V-Unit - Videothek Management Software\n\nEntwickelt im Zuge des Java Programmierpraktikums an der Universität Osnabrück im September 2008.\n\n(C) 2008 Waldemar Smirnow, Volha Baranouskaya, Andie Hoffmann, Christopher Bertels\n\nKontakt:\nWaldemar Smirnow (wsmirnow@uos.de)\nVolha Baranouskaya (vbaranou@uos.de)\nAndie Hoffmann (andhoffm@uos.de)\nChristopher Bertels (chbertel@uos.de)\n\n===========================================================\n\nHinweis:\nAlle verwendeten Icons (außer V-Unit.ico / V-Unit logo) sind Eigentum von Mark James.\n(C) Mark James, Website: http://www.famfamfam.com");
	    jScrollPane1.setViewportView(textPane);
	
	    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	    getContentPane().setLayout(layout);
	    layout.setHorizontalGroup(
	      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
	          .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
	        .addContainerGap())
	    );
	    layout.setVerticalGroup(
	      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
	        .addGap(18, 18, 18)
	        .addComponent(okButton)
	        .addContainerGap())
	    );
	    
	    pack();
	  }// </editor-fold>

	private void okButtonActionPerformed(ActionEvent e)
	{
		this.dispose();
	}
		
	  // Variables declaration - do not modify
	  private javax.swing.JButton okButton;
	  private javax.swing.JScrollPane jScrollPane1;
	  private javax.swing.JTextPane textPane;
	  // End of variables declaration
  
}