package GUI.dialogs;

import javax.swing.JFileChooser;

public class SettingsDialog extends javax.swing.JDialog
{
	private static final long serialVersionUID = 4874571449595555298L;
	
	private String invoiceFolder;
	private String warningInvoiceFolder;
	private String warningFolder;
	private boolean setCurrentDateOnStartup;

	/** Creates new form SettingsDialog */
	public SettingsDialog(java.awt.Frame parent, boolean modal)
	  {
	    super(parent, modal);
	    initComponents();
	  }
  
	  /** This method is called from within the constructor to
	   * initialize the form.
	   * WARNING: Do NOT modify this code. The content of this method is
	   * always regenerated by the Form Editor.
	   */
	  // <editor-fold defaultstate="collapsed" desc="Generated Code">
	  private void initComponents()
	  {
	
	    jFileChooser2 = new javax.swing.JFileChooser();
	    jTabbedPane1 = new javax.swing.JTabbedPane();
	    settingsPanel = new javax.swing.JPanel();
	    setCurrentDateCheckbox = new javax.swing.JCheckBox();
	    invoiceFolderFileChooser = new javax.swing.JFileChooser();
	    jPanel1 = new javax.swing.JPanel();
	    jLabel2 = new javax.swing.JLabel();
	    invoiceFolderSetButton = new javax.swing.JButton();
	    invoiceFolderLabel = new javax.swing.JLabel();
	    jLabel3 = new javax.swing.JLabel();
	    warningInvoiceFolderLabel = new javax.swing.JLabel();
	    warningInvoiceFolderSetButton = new javax.swing.JButton();
	    jPanel2 = new javax.swing.JPanel();
	    warningFolderLabel = new javax.swing.JLabel();
	    jLabel4 = new javax.swing.JLabel();
	    warningFolderSetButton = new javax.swing.JButton();
	    priceCategoriesPanel = new javax.swing.JPanel();
	    jScrollPane1 = new javax.swing.JScrollPane();
	    priceCategoryTable = new javax.swing.JTable();
	    addButton = new javax.swing.JButton();
	    deleteButton = new javax.swing.JButton();
	    jLabel1 = new javax.swing.JLabel();
	    okButton = new javax.swing.JButton();
	    cancelButton = new javax.swing.JButton();
	
	    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	    setTitle("Einstellungen");
	    setResizable(false);
	
	    setCurrentDateCheckbox.setText("Tagesdatum bei Programmstart festlegen");
	    setCurrentDateCheckbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	
	    invoiceFolderFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
	    invoiceFolderFileChooser.addActionListener(new java.awt.event.ActionListener()
	    {
	      public void actionPerformed(java.awt.event.ActionEvent evt)
	      {
	        invoiceFolderFileChooserActionPerformed(evt);
	      }
	    });
	
	    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quittungen"));
	
	    jLabel2.setText("Ausleih-Quittungen ablegen in:");
	
	    invoiceFolderSetButton.setText("Ordner festlegen");
	    invoiceFolderSetButton.addActionListener(new java.awt.event.ActionListener()
	    {
	      public void actionPerformed(java.awt.event.ActionEvent evt)
	      {
	        invoiceFolderSetButtonActionPerformed(evt);
	      }
	    });
	
	    invoiceFolderLabel.setText("/quittungen/");
	
	    jLabel3.setText("Mahnungs-Quittungen ablegen in:");
	
	    warningInvoiceFolderLabel.setText("/quittungen/mahnungen/");
	
	    warningInvoiceFolderSetButton.setText("Ordner festlegen");
	    warningInvoiceFolderSetButton.addActionListener(new java.awt.event.ActionListener()
	    {
	      public void actionPerformed(java.awt.event.ActionEvent evt)
	      {
	        warningInvoiceFolderSetButtonActionPerformed(evt);
	      }
	    });
	
	    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	    jPanel1.setLayout(jPanel1Layout);
	    jPanel1Layout.setHorizontalGroup(
	      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(jPanel1Layout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	          .addComponent(invoiceFolderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
	          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
	          .addComponent(warningInvoiceFolderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
	          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
	          .addComponent(invoiceFolderSetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
	          .addComponent(warningInvoiceFolderSetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
	        .addContainerGap())
	    );
	    jPanel1Layout.setVerticalGroup(
	      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(jPanel1Layout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addGap(11, 11, 11)
	        .addComponent(invoiceFolderLabel)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(invoiceFolderSetButton)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addGap(11, 11, 11)
	        .addComponent(warningInvoiceFolderLabel)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(warningInvoiceFolderSetButton)
	        .addContainerGap())
	    );
	
	    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mahnungen"));
	
	    warningFolderLabel.setText("/mahnungen/");
	
	    jLabel4.setText("Ausleih-Quittungen ablegen in:");
	
	    warningFolderSetButton.setText("Ordner festlegen");
	    warningFolderSetButton.addActionListener(new java.awt.event.ActionListener()
	    {
	      public void actionPerformed(java.awt.event.ActionEvent evt)
	      {
	        warningFolderSetButtonActionPerformed(evt);
	      }
	    });
	
	    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	    jPanel2.setLayout(jPanel2Layout);
	    jPanel2Layout.setHorizontalGroup(
	      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(jPanel2Layout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	          .addComponent(warningFolderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
	          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
	          .addComponent(warningFolderSetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
	        .addContainerGap())
	    );
	    jPanel2Layout.setVerticalGroup(
	      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(jPanel2Layout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addGap(11, 11, 11)
	        .addComponent(warningFolderLabel)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(warningFolderSetButton)
	        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	    );
	
	    javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
	    settingsPanel.setLayout(settingsPanelLayout);
	    settingsPanelLayout.setHorizontalGroup(
	      settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addComponent(setCurrentDateCheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
	      .addGroup(settingsPanelLayout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addContainerGap())
	      .addGroup(settingsPanelLayout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addContainerGap())
	    );
	    settingsPanelLayout.setVerticalGroup(
	      settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(settingsPanelLayout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(setCurrentDateCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addContainerGap())
	    );
	
	    jTabbedPane1.addTab("Allgemeines", settingsPanel);
	
	    priceCategoryTable.setModel(new javax.swing.table.DefaultTableModel(
	      new Object [][]
	      {
	        {null, null, null}
	      },
	      new String []
	      {
	        "Nr.", "Name", "Preis"
	      }
	    )
	    {
	      Class[] types = new Class []
	      {
	        java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
	      };
	
	      public Class getColumnClass(int columnIndex)
	      {
	        return types [columnIndex];
	      }
	    });
	    priceCategoryTable.getTableHeader().setReorderingAllowed(false);
	    jScrollPane1.setViewportView(priceCategoryTable);
	    priceCategoryTable.getColumnModel().getColumn(0).setPreferredWidth(100);
	    priceCategoryTable.getColumnModel().getColumn(0).setMaxWidth(100);
	    priceCategoryTable.getColumnModel().getColumn(1).setPreferredWidth(1100);
	    priceCategoryTable.getColumnModel().getColumn(2).setPreferredWidth(400);
	
	    addButton.setText("Hinzufügen");
	    addButton.addActionListener(new java.awt.event.ActionListener()
	    {
	      public void actionPerformed(java.awt.event.ActionEvent evt)
	      {
	        addButtonActionPerformed(evt);
	      }
	    });
	
	    deleteButton.setText("Löschen");
	
	    javax.swing.GroupLayout priceCategoriesPanelLayout = new javax.swing.GroupLayout(priceCategoriesPanel);
	    priceCategoriesPanel.setLayout(priceCategoriesPanelLayout);
	    priceCategoriesPanelLayout.setHorizontalGroup(
	      priceCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(priceCategoriesPanelLayout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(priceCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
	          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, priceCategoriesPanelLayout.createSequentialGroup()
	            .addComponent(deleteButton)
	            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
	            .addComponent(addButton)))
	        .addContainerGap())
	    );
	    priceCategoriesPanelLayout.setVerticalGroup(
	      priceCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(priceCategoriesPanelLayout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(priceCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	          .addComponent(addButton)
	          .addComponent(deleteButton))
	        .addGap(11, 11, 11)
	        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
	        .addContainerGap())
	    );
	
	    jTabbedPane1.addTab("Preiskategorien", priceCategoriesPanel);
	
	    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
	    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	    jLabel1.setText("Einstellungen");
	
	    okButton.setText("OK");
	    okButton.addActionListener(new java.awt.event.ActionListener()
	    {
	      public void actionPerformed(java.awt.event.ActionEvent evt)
	      {
	        okButtonActionPerformed(evt);
	      }
	    });
	
	    cancelButton.setText("Abbrechen");
	    cancelButton.addActionListener(new java.awt.event.ActionListener()
	    {
	      public void actionPerformed(java.awt.event.ActionEvent evt)
	      {
	        cancelButtonActionPerformed(evt);
	      }
	    });
	
	    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	    getContentPane().setLayout(layout);
	    layout.setHorizontalGroup(
	      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(layout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	          .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
	          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
	          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	            .addComponent(cancelButton)
	            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
	        .addContainerGap())
	    );
	    layout.setVerticalGroup(
	      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(layout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(jLabel1)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	          .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
	          .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
	        .addContainerGap())
	    );
	
	    pack();
	  }// </editor-fold>
	
	  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)                                         
	  {                                             
	    // config setzen und so...
	    
	    this.dispose();
	  }                                        
	
	  private void invoiceFolderFileChooserActionPerformed(java.awt.event.ActionEvent evt)                                                         
	  {                                                             
	    // TODO add your handling code here:
	}                                                        
	
	  private void invoiceFolderSetButtonActionPerformed(java.awt.event.ActionEvent evt)                                                       
	  {                                                           
	    if(invoiceFolderFileChooser.showDialog(this, "Ordner auswählen") == JFileChooser.APPROVE_OPTION)
	    {
	      this.invoiceFolder = invoiceFolderFileChooser.getSelectedFile().getPath();
	      this.invoiceFolderLabel.setText(this.invoiceFolder);
	    }
	  }                                                      
	
	  private void warningInvoiceFolderSetButtonActionPerformed(java.awt.event.ActionEvent evt)                                                              
	  {                                                                  
	    if(invoiceFolderFileChooser.showDialog(this, "Ordner auswählen") == JFileChooser.APPROVE_OPTION)
	    {
	      this.warningInvoiceFolder = invoiceFolderFileChooser.getSelectedFile().getPath();
	      this.warningInvoiceFolderLabel.setText(this.warningInvoiceFolder);
	    }
	}                                                             
	
	  private void warningFolderSetButtonActionPerformed(java.awt.event.ActionEvent evt)
	  {
	    if(invoiceFolderFileChooser.showDialog(this, "Ordner auswählen") == JFileChooser.APPROVE_OPTION)
	    {
	      this.warningFolder = invoiceFolderFileChooser.getSelectedFile().getPath();
	      this.warningFolderLabel.setText(this.warningFolder);
	    }
	}
	
	  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)
	  {
	    this.dispose();
	  }
	
	  private void addButtonActionPerformed(java.awt.event.ActionEvent evt)
	  {
	    
	  }
	  
	  
	  // Variables declaration - do not modify
	  private javax.swing.JButton addButton;
	  private javax.swing.JButton cancelButton;
	  private javax.swing.JButton deleteButton;
	  private javax.swing.JFileChooser invoiceFolderFileChooser;
	  private javax.swing.JLabel invoiceFolderLabel;
	  private javax.swing.JButton invoiceFolderSetButton;
	  private javax.swing.JFileChooser jFileChooser2;
	  private javax.swing.JLabel jLabel1;
	  private javax.swing.JLabel jLabel2;
	  private javax.swing.JLabel jLabel3;
	  private javax.swing.JLabel jLabel4;
	  private javax.swing.JPanel jPanel1;
	  private javax.swing.JPanel jPanel2;
	  private javax.swing.JScrollPane jScrollPane1;
	  private javax.swing.JTabbedPane jTabbedPane1;
	  private javax.swing.JButton okButton;
	  private javax.swing.JPanel priceCategoriesPanel;
	  private javax.swing.JTable priceCategoryTable;
	  private javax.swing.JCheckBox setCurrentDateCheckbox;
	  private javax.swing.JPanel settingsPanel;
	  private javax.swing.JLabel warningFolderLabel;
	  private javax.swing.JButton warningFolderSetButton;
	  private javax.swing.JLabel warningInvoiceFolderLabel;
	  private javax.swing.JButton warningInvoiceFolderSetButton;
	  // End of variables declaration
	  
	}
